version: '3.8'

services:
  turnstile:
    build: .
    container_name: turnstile
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_QR_MANAGER=${ACCESS_QR_MANAGER}
      - JWT_PUBLIC_KEY_PEM=${JWT_PUBLIC_KEY_PEM}